import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

/**
 * Returns true when Claude Code is one of the target agents.
 * @param {string[]} agents
 * @returns {boolean}
 */
export function shouldGenerateClaudeMd(agents = []) {
  return agents.includes("claude-code");
}

/**
 * Recursively collects markdown files from a directory.
 * @param {string} dir
 * @returns {string[]}
 */
function collectMarkdownFiles(dir) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }

  const files = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    const isDir =
      entry.isDirectory() || (entry.isSymbolicLink() && statSync(fullPath).isDirectory());
    if (isDir) {
      files.push(...collectMarkdownFiles(fullPath));
      continue;
    }

    const isFile = entry.isFile() || entry.isSymbolicLink();
    if (isFile && entry.name.toLowerCase().endsWith(".md")) {
      files.push(fullPath);
    }
  }

  return files;
}

/**
 * Strips YAML frontmatter and extracts `name` and `description` fields.
 * @param {string} markdown
 * @returns {{ body: string, fmName: string|null, fmDescription: string|null }}
 */
function parseFrontmatter(markdown) {
  if (!markdown.startsWith("---")) {
    return { body: markdown, fmName: null, fmDescription: null };
  }

  const endIdx = markdown.indexOf("\n---", 3);
  if (endIdx === -1) {
    return { body: markdown, fmName: null, fmDescription: null };
  }

  const block = markdown.slice(3, endIdx);
  const body = markdown.slice(endIdx + 4).replace(/^\n+/, "");

  let fmName = null;
  let fmDescription = null;

  for (const line of block.split(/\r?\n/)) {
    const nameMatch = line.match(/^name:\s*["']?(.+?)["']?\s*$/);
    if (nameMatch) fmName = nameMatch[1];

    const descMatch = line.match(/^description:\s*["']?(.+?)["']?\s*$/);
    if (descMatch) fmDescription = descMatch[1];
  }

  return { body, fmName, fmDescription };
}

/**
 * Extracts a compact summary from a markdown document.
 * Strips YAML frontmatter and uses its `description` when available.
 * @param {string} markdown
 * @returns {{ title: string|null, summary: string|null }}
 */
export function summarizeMarkdown(markdown) {
  const { body, fmName, fmDescription } = parseFrontmatter(markdown);

  const lines = body.split(/\r?\n/);
  let title = null;
  let summary = null;
  let inCodeFence = false;
  const paragraph = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (line.startsWith("```")) {
      inCodeFence = !inCodeFence;
      continue;
    }

    if (inCodeFence) continue;

    if (!title && line.startsWith("#")) {
      title = line.replace(/^#+\s*/, "").trim() || null;
      continue;
    }

    if (fmDescription) continue;

    if (!line) {
      if (paragraph.length > 0) {
        summary = paragraph.join(" ").trim();
        break;
      }
      continue;
    }

    if (/^#{1,6}\s/.test(line)) continue;
    if (/^[-*_]{3,}$/.test(line)) continue;
    if (/^[-*]\s+/.test(line) && paragraph.length === 0) continue;
    if (/^\d+\.\s+/.test(line) && paragraph.length === 0) continue;
    if (/^[>|`]/.test(line)) continue;

    paragraph.push(line);
  }

  if (fmDescription) {
    summary = fmDescription;
  } else if (!summary && paragraph.length > 0) {
    summary = paragraph.join(" ").trim();
  }

  if (!title) title = fmName;

  if (summary) {
    summary = summary.replace(/\s+/g, " ");
    if (summary.length > 300) {
      summary = `${summary.slice(0, 297).trimEnd()}...`;
    }
  }

  return { title, summary };
}

const SECTION_START = "<!-- autoskills:start -->";
const SECTION_END = "<!-- autoskills:end -->";

/**
 * Builds the autoskills section content from installed Claude Code skills.
 * @param {string} projectDir
 * @param {string} skillsDir
 * @param {string[]} markdownFiles
 * @returns {string}
 */
function buildSection(projectDir, skillsDir, markdownFiles) {
  const entries = [];
  for (const filePath of markdownFiles) {
    const relativePath = relative(projectDir, filePath).replaceAll("\\", "/");
    const innerPath = relative(skillsDir, filePath).replaceAll("\\", "/");
    const skillName = innerPath.split("/")[0] || "unknown-skill";
    const fileName = innerPath.split("/").slice(1).join("/") || innerPath;
    const markdown = readFileSync(filePath, "utf-8");
    const { title, summary } = summarizeMarkdown(markdown);
    entries.push({ skillName, relativePath, fileName, title, summary });
  }

  const grouped = new Map();
  for (const entry of entries) {
    if (!grouped.has(entry.skillName)) {
      grouped.set(entry.skillName, []);
    }
    grouped.get(entry.skillName).push(entry);
  }

  const lines = [
    SECTION_START,
    "",
    "Summary generated by `autoskills`. Check the full files inside `.claude/skills`.",
    "",
  ];

  for (const [, skillEntries] of grouped) {
    const main = skillEntries.find((e) => /^SKILL\.md$/i.test(e.fileName));
    const refs = skillEntries.filter((e) => e !== main);

    const heading = main?.title || refs[0]?.title || skillEntries[0].skillName;
    const description = main?.summary;

    lines.push(`## ${heading}`);
    lines.push("");

    if (description) {
      lines.push(description);
      lines.push("");
    }

    if (main) {
      lines.push(`- \`${main.relativePath}\``);
    }

    for (const ref of refs) {
      const label = ref.title || ref.fileName;
      const desc = ref.summary ? `: ${ref.summary}` : "";
      lines.push(`- \`${ref.relativePath}\`${desc}`);
    }

    lines.push("");
  }

  lines.push(SECTION_END);
  return lines.join("\n");
}

/**
 * Builds a CLAUDE.md summary from installed Claude Code skills.
 * Preserves any user content outside the `<!-- autoskills:start/end -->` delimiters.
 * @param {string} projectDir
 * @returns {{ generated: boolean, outputPath: string, files: number }}
 */
export function generateClaudeMd(projectDir) {
  const skillsDir = join(projectDir, ".claude", "skills");
  const outputPath = join(projectDir, "CLAUDE.md");

  if (!existsSync(skillsDir)) {
    return { generated: false, outputPath, files: 0 };
  }

  const markdownFiles = collectMarkdownFiles(skillsDir).sort((a, b) => a.localeCompare(b));
  if (markdownFiles.length === 0) {
    return { generated: false, outputPath, files: 0 };
  }

  const section = buildSection(projectDir, skillsDir, markdownFiles);

  let content;
  if (existsSync(outputPath)) {
    const existing = readFileSync(outputPath, "utf-8");
    const startIdx = existing.indexOf(SECTION_START);
    const endIdx = existing.indexOf(SECTION_END);

    if (startIdx !== -1 && endIdx !== -1) {
      const before = existing.slice(0, startIdx);
      const after = existing.slice(endIdx + SECTION_END.length);
      content = `${before}${section}${after}`;
    } else {
      content = `${existing.trimEnd()}\n\n${section}\n`;
    }
  } else {
    content = `# CLAUDE.md\n\n${section}\n`;
  }

  writeFileSync(outputPath, content);
  return { generated: true, outputPath, files: markdownFiles.length };
}
